CONSOLE_WIDTH: int = 60
CONSOLE_HEIGHT: int = 32

TILE_SIZE: int = 20
MAGNIFICATION: float = 2.0

STAGE_WIDTH: int = 128
STAGE_HEIGHT: int = 128
STAGE_PANEL_WIDTH: int = CONSOLE_WIDTH
STAGE_PANEL_HEIGHT: int = CONSOLE_HEIGHT
# STAGE_PANEL_WIDTH: int = (CONSOLE_WIDTH // 3) * 2
# STAGE_PANEL_HEIGHT: int = (CONSOLE_HEIGHT // 4) * 3
SIDE_PANEL_WIDTH: int = CONSOLE_WIDTH - STAGE_PANEL_WIDTH
SIDE_PANEL_HEIGHT: int = CONSOLE_HEIGHT
LOG_PANEL_HEIGHT: int = (CONSOLE_HEIGHT // 4)

DEBUG: bool = False
DEVELOP: bool = True
VIEW_RADIUS: int = 10 if DEBUG is False else 30
