import math

CONSOLE_WIDTH: int = 120
CONSOLE_HEIGHT: int = 40

STAGE_WIDTH: int = 65
STAGE_HEIGHT: int = math.ceil(STAGE_WIDTH / 2)

TILE_SIZE: int = 20
DEFAULT_TILESET: str = "Simulacra"

FULLSCREEN: bool = True

STAGE_PANEL_WIDTH = CONSOLE_WIDTH
STAGE_PANEL_HEIGHT = CONSOLE_HEIGHT
# STAGE_PANEL_WIDTH: int = (CONSOLE_WIDTH // 3) * 2
# STAGE_PANEL_HEIGHT: int = ((CONSOLE_HEIGHT // 4) * 3)
SIDE_PANEL_WIDTH: int = CONSOLE_WIDTH - STAGE_PANEL_WIDTH
SIDE_PANEL_HEIGHT: int = CONSOLE_HEIGHT
LOG_PANEL_HEIGHT: int = (CONSOLE_HEIGHT // 4)

DEBUG: bool = False
DEVELOP: bool = True
VIEW_RADIUS: int = 10 if DEBUG is False else 30
