CONSOLE_WIDTH: int = 144 + 32 + 16
CONSOLE_HEIGHT: int = 48 + 8
STAGE_SIZE: int = 32

STAGE_WIDTH: int = STAGE_SIZE * 2
STAGE_HEIGHT: int = STAGE_SIZE

TILE_SIZE: int = 16
DEFAULT_TILESET: str = "Simulacra"

FULLSCREEN: bool = True

STAGE_PANEL_WIDTH: int = (CONSOLE_WIDTH // 3) * 2
# STAGE_PANEL_HEIGHT: int = ((CONSOLE_HEIGHT // 4) * 3)
STAGE_PANEL_HEIGHT = CONSOLE_HEIGHT
SIDE_PANEL_WIDTH: int = CONSOLE_WIDTH - STAGE_PANEL_WIDTH
SIDE_PANEL_HEIGHT: int = CONSOLE_HEIGHT
LOG_PANEL_HEIGHT: int = (CONSOLE_HEIGHT // 4)

DEBUG: bool = False
DEVELOP: bool = True
VIEW_RADIUS: int = 10 if DEBUG is False else 30
